Allow skipping verification for Collections
aryehraber/statamic-captcha pull request #11
Opened 2021-01-25 13:39 UTC by aryehraber

This PR is an alternate approach to https://github.com/aryehraber/statamic-captcha/pull/10, allowing skipping Captcha verification for certain fields using an additional config option. Eg:

```php
return [
    // ...
    'collections' => [
        'pages' => [
            'skip_fields' => ['foo', 'bar'],
        ],
        'blog',
        'other',
    ],
    // ...
];
```

@edalzell It would be great if you could review this and see if this works for your use case

2021-01-25 14:49 UTC, edalzell commented
I will give it a try @aryehraber, but what about the `_token` field (CSRF)?

2021-01-25 15:55 UTC, aryehraber commented
Good catch, my tests didn't go through a "real" form so I didn't need one. Will need to filter that out before the comparison 👍

2021-01-25 20:34 UTC, aryehraber commented
@edalzell Ok just pushed an update! I ended up building a quick Workshop-like endpoint to edit CP content from the front-end for testing, so I'm fairly confident this works as expected now, but still curious to hear your take on it!

2021-01-25 22:49 UTC, edalzell commented
@aryehraber looks good but I don't use recaptcha on this page so we'll have to see a good way to configure that perhaps.

I'll take a look at this this week. Thanks!

2021-01-26 05:00 UTC, edalzell requested changes
I'd remove the `g-recaptcha-response` as it's not default in Statamic (and they may not be using it). If folks are using it, they can add it themselves to the `skip_fields` list.

2021-01-26 15:29 UTC, aryehraber commented
Hmm yeah, I guess it won't be there if it's on a form _not_ using Captcha (which this PR is trying to solve), so will remove it again for the time-being until some issues regarding this are reported.

2021-01-27 03:49 UTC, edalzell approved these changes

2021-01-27 03:49 UTC, edalzell commented
Looks awesome, thanks! Merge away!

2021-01-27 08:48 UTC, merged